apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-end2-end
  labels:
    app: go-end2-end
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-end2-end
  template:
    metadata:
      labels:
        app: go-end2-end
    spec:
      containers:
        - name: go-end2-end
          image: rifky86/go-end2-end:v1
          ports:
            - containerPort: 8080
