apiVersion: v1
kind: Service
metadata:
  name: go-end2-end
  labels:
    app: go-end2-end
spec:
  selector:
    app: go-end2-end
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30291
  type: NodePort
