
replicaCount: 1
image:
  repository: rifky86/go-end2-end
  pullPolicy: IfNotPresent
  tag: "stg-1-13726378263"

ingress:
  enabled: true
  className: ""
  annotations: {}
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: ImplementationSpecific


imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}
service:
  type: ClusterIP
  port: 80


  tls: []
resources: {}
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}
tolerations: []

affinity: {}
